---
title: "Thomas Fire Progression"
author: "Oceana Tavasieff"
date: "10/23/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load packages}
library(tidyverse)
library(readxl)
library(lubridate)
```

```{r Load Data}
#Remember excel files can have multiple sheets!! ( unlike csv)
excel_sheets("Input_Data/week1/2013_2019_CALFIRE_Redbook.xlsx")
# Returns the names of the sheets, of which there are two

cal_fire_metadata = read_excel("Input_Data/week1/2013_2019_CALFIRE_Redbook.xlsx", sheet=1)
cal_fire_data= read_excel("Input_Data/week1/2013_2019_CALFIRE_Redbook.xlsx", sheet=2)

#argument sheet in read_excel can accept integer input (number of sheet) or character ("Name of sheet")

```


## Explore Thomas Fire data and generate some analysis

```{r Data Exploration}
names(cal_fire_data)

#Relationship between vegetation type and size/destruction of fire?

unique(cal_fire_data$Veg_Type)

cal_fire_metadata[c(6,7,8,9,10),c(1,2)] #View codes for vegetation type in metadata
unique(cal_fire_data$Veg_Type)

# Do some causes of fire lead to more destruction than others?
mode("cal_fire_data$Cause")
unique(cal_fire_data$Cause)
```


```{r}
veg_acres_plot <- cal_fire_data %>% ggplot(aes(x = Veg_Type, y= Total_Acres_Burned)) + geom_boxplot(aes(x = Veg_Type, y= Total_Acres_Burned)) + xlab("Vegetation Type") + ylab("Total Acres Burned")

veg_acres_plot
#Looking at this plot I can see that there are many data points outside the box and whisker plots. Additionally, that vegetation is classed in different combinations and orders (e.g. BGT vs TBG). 

#NEXT STEP: Assume order of vegetation code does not matter:


cal_fire_data_veg <- cal_fire_data %>% mutate(Veg_Type = ifelse(Veg_Type == "TB", "BT", Veg_Type), Veg_Type = ifelse(Veg_Type == "GT", "TG", Veg_Type), Veg_Type = ifelse(Veg_Type == "BGT", "TBG", Veg_Type))

unique(cal_fire_data_veg$Veg_Type)

veg_acres_plot_joined <- cal_fire_data_veg %>% ggplot(aes(x = Veg_Type, y= Total_Acres_Burned)) + geom_boxplot(aes(x = Veg_Type, y= Total_Acres_Burned)) + xlab("Vegetation Type") + ylab("Total Acres Burned")

veg_acres_plot_joined

#Timber (T), Brush & Timber (BT) and Timber, Brush & Grass (TBG) fires seem to be the most destructive.
```


```{r}
cause_acres_plot <- cal_fire_data %>% ggplot(aes(x = Cause, y= Total_Acres_Burned)) + geom_boxplot(aes(x = Cause, y= Total_Acres_Burned)) + xlab("Cause") + ylab("Total Acres Burned") + theme(text=element_text(size = 7))

cause_acres_plot

#greatest damage occurred in fires with Cause= "Campfire, Electrical, Lightning, Shooting"
```

```{r}
#Let's take a closer look at the most damaging causes

major_cause_plot <- cal_fire_data %>% filter(Cause %in% c("CAMPFIRE", "ELECTRICAL POWER", "LIGHTNING", "SHOOTING")) %>% ggplot(aes(x = Cause, y= Total_Acres_Burned)) + geom_boxplot(aes(x = Cause, y= Total_Acres_Burned)) + xlab("Cause") + ylab("Total Acres Burned") + theme(text=element_text(size = 12))
major_cause_plot

#Lightning has highest average acres burned but shooting has largest IQR. 
```





